QuantEcon/lecture-python-advanced.myst

lectures/_config.yml
This PR updates mathjax math macros to fix https://github.com/QuantEcon/lecture-python-advanced.myst/issues/6
=> FIX: update math macros for argmaxx and argmin

environment.yml
This is a maintenance update to our software environment due to an issue with nbdime -> jupyter_server not updating tornado to a compatible version.
=> FIX: update environment for quantecon

lectures/discrete_dp.md
This PR adjusts figures' size in [discrete_dp](https://python-advanced.quantecon.org/discrete_dp.html). I thought the current size is a little large.
```Left```: before this PR ```Right```: after this PR
cc: @mmcky
=> [discrete_dp]adjust figure sizes in lecture

lectures/tax_smoothing_1.md
The link was split across two lines
Here is the comparison between ```MyST``` before this PR (```LHS```) and after this PR (```RHS```).  So it works ok after this PR.
cc: @mmcky
=> [tax_smoothing_1] fix broken link

lectures/tax_smoothing_3.md
The link was split across two lines.
Here is the comparison between ```MyST``` before this PR (```LHS```) and after this PR (```RHS```).  So it works ok after this PR.
cc: @mmcky
=> [tax_smoothing_3] fix broken link

lectures/matsuyama.md
This PR adjusts figures' size in [matsuyama](https://5ff58313b5fa65a2d9f2bcf6--wonderful-lalande-528d1c.netlify.app/matsuyama.html#basin-of-attraction). 
```Left```: before this PR ```Right```: after this PR
cc: @mmcky
=> [matsuyama]adjust figure sizes in lecture

lectures/arma.md
This PR fixes a broken list [here.](https://5ff58313b5fa65a2d9f2bcf6--wonderful-lalande-528d1c.netlify.app/arma.html#other-reading)
Here is the comparison between ```MyST``` before this PR (```LHS```) and after this PR (```RHS```).  So it works ok after this PR.
cc: @mmcky
=> [arma]fix broken list

lectures/BCG_complete_mkts.md
This PR fixes unexpected list which occurs only in ```MyST```.
Here is the comparison between ```MyST``` before this PR (```LHS```) and after this PR (```RHS```).  So it works ok after this PR (after the second commit).
Here is [the section](https://python-advanced.quantecon.org/BCG_complete_mkts.html#Code) in ```RST``` website.
cc: @mmcky
=> [BCG_complete_mkts]fix unexpected list

lectures/black_litterman.md, lectures/chang_credible.md, lectures/growth_in_dles.md
This PR fixes #16 to fix malformed `blockquote` context when using `$$` displaymath
=> FIX: blockquote syntax when using displaymath

lectures/tax_smoothing_2.md
Hi @mmcky , this PR updates the figure sizes issue mentioned by #14 in lecture [11_tax_smoothing_2](https://github.com/QuantEcon/lecture-python-advanced.myst/compare/11_tax_smoothing_2%5D-Adjust-Figure-Sizes?expand=1#diff-9f30eae03bdefea6076385b7369a49dd166097745b326e7fe23f53febc23703c) (left: before the PR; right: with the PR):
=> [11_tax_smoothing_2] Adjust Figure Sizes

lectures/tax_smoothing_3.md
Hi @mmcky , this PR updates the figure sizes issue mentioned by #14 in lecture [12_tax_smoothing_3](https://github.com/QuantEcon/lecture-python-advanced.myst/compare/12_tax_smoothing_3%5D-Adjust-Figure-Sizes?expand=1#diff-6344876214710579e6204d51fd13b59c2f327252aa69925d838dc6a433318fc5) (left: before the PR; right: with the PR):
=> [12_tax_smoothing_3] Adjust Figure Sizes

lectures/permanent_income_dles.md
Hi @mmcky , this PR updates the figure sizes issue mentioned by #14 in lecture [22_permanent_income_dles](https://github.com/QuantEcon/lecture-python-advanced.myst/compare/22_permanent_income_dles-Adjust-Figure-Sizes?expand=1#diff-866e056c05932e9c646e44b4b57892f8580c7ebe1d4135b975d305a902b4c3a9) (left: before the PR; right: with the PR):
=> [22_permanent_income_dles] Adjust Figure Sizes

lectures/opt_tax_recur.md
Hi @mmcky , this PR updates the figure sizes issue mentioned by #14 in lecture [39_opt_tax_recur.md ](https://github.com/QuantEcon/lecture-python-advanced.myst/compare/39_opt_tax_recur%5D-Adjust-Figure-Sizes?expand=1#diff-c3404237063f860075403d27e982cdd2c7277be621e461b4970abc3dc3059529) (It seems that the code cells in this lecture are unable to be executed).
=> [39_opt_tax_recur] Adjust Figure Sizes

lectures/smoothing.md
Hi @mmcky , this PR updates the figure sizes issue mentioned by #14 in lecture [6_smoothing](https://github.com/QuantEcon/lecture-python-advanced.myst/compare/6_smoothing%5D-Adjust-Figure-Sizes?expand=1#diff-41ad7530a662301a5f70e23ffe8b5ddfe8d6f9a10212cf7cfff7a2de46438c94) (left: before the PR; right: with the PR):
=> [6_smoothing] Adjust Figure Sizes

lectures/smoothing_tax.md
Hi @mmcky , this PR updates the figure sizes issue mentioned by #14 in lecture [7_smoothing_tax](https://github.com/QuantEcon/lecture-python-advanced.myst/compare/7_smoothing_tax%5D-Adjust-Figure-Sizes?expand=1#diff-247d1a6e2db0ffe50d593b5775dae277ca4da798af8dbc14a7d829e40db16d40) (left: before the PR; right: with the PR):
=> [7_smoothing_tax] Adjust Figure Sizes

lectures/arma.md
Hi @mmcky , this PR updates the figure sizes issue mentioned by #14 in lecture [27_arma](https://github.com/QuantEcon/lecture-python-advanced.myst/compare/27_arma%5D-Adjust-Figure-Sizes?expand=1#diff-a07fee5b24acdc5aa349d9001ccb3c1a5b2a52e9af2e20b26601552d9553031f) (left: before the PR; right: with the PR):
=> [27_arma] Adjust Figure Sizes

lectures/BCG_complete_mkts.md
Hi @mmcky , this PR updates the figure sizes issue mentioned by #14 in lecture [35_BCG_complete_mkts](https://github.com/QuantEcon/lecture-python-advanced.myst/compare/35_BCG_complete_mkts%5D-Adjust-Figure-Sizes?expand=1#diff-eabfe17ee4d6f7807b8c5e4480dba5a49162f7458ea1d22546f32282fa39be3a).
=> [35_BCG_complete_mkts] Adjust Figure Sizes

lectures/discrete_dp.md
Hi @mmcky , this PR updates the figure sizes issue mentioned by #14 in lecture [4_discrete_dp](https://github.com/QuantEcon/lecture-python-advanced.myst/compare/discrete_dp%5D-Adjust-Figure-Sizes?expand=1#diff-d11aea98d3064d266c4e277d6731d4451bcfe1031bc3a10b13a2f4f0030b060e) (left: before the PR; right: with the PR):
=> [4_discrete_dp] Adjust Figure Sizes

.github/workflows/ci.yml
This PR updates the cache to fetch `_build` folder from an independent `cache.yml` workflow which we can set to update on a schedule.
=> [CI] fetch build cache from cache workflow

lectures/amss.md, lectures/amss2.md, lectures/amss3.md
HI @mmcky , this fix #65 and #64 in the following lectures:
- [amss](https://quantecon.github.io/lecture-python-advanced.myst/amss.html)
- [amss2](https://quantecon.github.io/lecture-python-advanced.myst/amss2.html)
- [amss3](https://quantecon.github.io/lecture-python-advanced.myst/amss3.html)
It also fixes `tags` for `collapse-20` in these lectures
=> [amss] [amss2] [amss3] scroll outputs

.github/workflows/publish.yml
Adding the `cached` build directory to the `publish` workflow fixes an issue involving interactive plots (such as `plotly`)
It appears that `html` build needs to be run first, prior to building `download notebooks` and/or `pdf` files so using the `cache` will resolve this.
The added benefit is that `publish` workflows will be a lot quicker.
=> FIX: add in cached _build folder due to plotly bug

environment.yml
This upgrades `sphinx-tojupyter==0.1.2` which brings in `chapter` context in equation numbers for the download notebooks.
=> ENH: Upgrade sphinx-tojupyer=0.1.2

lectures/knowing_forecasts_of_others.md
A few errors were encountered during pdf build.
1) Having multiple labels, inside a math environment. one of which was unnecessary, so have removed it.
2) Removing `eqnarray` from inside a `$$` environment, and using `aligned` instead which is compatible. Also removing the second `&` of `& = &` for proper alignment of equations in the new altered version.
3) Removing `$` from code statements like  `display(Latex(f'One-noise structure: ${round(p_one, 6)}$'))`, as it was unnecessary and was throwing 
```
[544] [545] [546] [547] [548] [549]
! Missing } inserted.
<inserted text> 
}
l.30537 ...-noise structure: $0.324062$\end{split}
```
=>  Changes in `knowing forecasts of others` for pdf build

lectures/_config.yml
This will enable direct `\begin{align}` to be used by enabling the `amsmath` extension to myst-parser
=> [asset-pricing-lph] enable myst-extensions including amsmath

lectures/discrete_dp.md
Hi @jstac , this PR corrects a possible minor typo in lecture [discrete_dp](https://python-advanced.quantecon.org/discrete_dp).
=> [discrete_dp] a possible minor typo

lectures/_config.yml, lectures/muth_kalman.md, lectures/orth_proj.md, lectures/stationary_densities.md
Hi @jstac and @mmcky,
I have migrated the first part of the lecture to use sphinx-exercise for the first section: Tools and Techniques.
Here is a summary of places to look at when reviewing this PR: 
1. I changed the _config.yml to enable spinx-exercise and drop-down solutions;
2. In lecture [4. Discrete State Dynamic Programming](https://63077285fc58d3007638c3a0--wonderful-lalande-528d1c.netlify.app/discrete_dp.html#id11), I think the exercise in it is more like a worked example rather than for students to practice themself. Thus, I did not change the style of this exercise. Please kindly let me know if you think it should also be migrated to sphinx-exercise (I think sphinx-exercise does not support adding sections within it as well);
3. A warning and a potential typo were fixed. Please …
=> [ENH] Migrate exercise and solutions: Part 1

lectures/knowing_forecasts_of_others.md
fixes https://github.com/QuantEcon/lecture-python-advanced.myst/issues/66
I have also removed the hard coding of website url in citation text. Let me know if that's okay. 
Does the website have more such citations? Will check.
=> 🐛 FIX: Correcting citations

.github/workflows/ci.yml, environment.yml, lectures/_config.yml, lectures/five_preferences.md, lectures/knowing_forecasts_of_others.md
This PR upgrades to `jupyter-book==0.15.1` + associated packages
=> ENH: Upgrade to jupyter-book==0.15.1 + associated packages

lectures/robustness.md
=> Fix quantecon namespace updates

lectures/knowing_forecasts_of_others.md
This PR fixes some malformed links and moves them to `cite` links.
=> FIX: links to bibliography

lectures/five_preferences.md
=> Fix the Bisection Issue in `five_preferences.md`

lectures/arellano.md
Simplify probability computations.
=> [arellano] Simplify probability computations

environment.yml, lectures/_config.yml, lectures/intro.md
=> MAINT: upgrade quantecon-book-theme and author information

.github/workflows/ci.yml, lectures/BCG_complete_mkts.md, lectures/BCG_incomplete_mkts.md, lectures/_static/lecture_specific/opt_tax_recur/recursive_allocation.py, lectures/coase.md, lectures/lucas_model.md, lectures/opt_tax_recur.md
This PR replaces all the occurences of `interpolation.interp` to `np.interp` now that `numba` supports `np.interp` directly.
=> Use np.interp instead of interpolation.interp

lectures/calvo_machine_learn.md
Hi @mmcky,
This PR is a minor fix for the Calvo Machine Learning Lecture.
I think it can be released after this PR is merged.
=> Minor Fixes to Calvo Machine Learning Lecture

environment.yml
Fixes #163.
Removed `numba` pin because the issue is fixed in `interpolation.py` in the new release `2.2.7`.
=> Remove numba pin

.github/dependabot.yml
This PR enables dependant for keeping versions up to date on GitHub Actions
=> ENH: enable dependabot for github actions versions

lectures/black_litterman.md
This PR optimizes the runtime of black_litterman lecture by using vectorization and numba jitting.
Fixes #183
=> Use vectorization and numba jitting for optimization

lectures/matsuyama.md
Remove ipywidgets from `matsuyama` lecture as it does not work with static pages and hangs the build.
Related to #183
=> Remove ipywidgets from `matsuyama` lecture

.github/workflows/cache.yml, .github/workflows/ci.yml, .github/workflows/linkcheck.yml, environment.yml, lectures/status.md
=> MAINT: update jupyter-book==1.0.3 and maintenance tasks

lectures/calvo_abreu.md
Hi @mmcky,
This PR fixes some notational inconsistency across calvo lectures. I am now migrating this to the repo for Tom's class.
=> [calvo_abreu] Fix a minor typo in Sustainable Plans for a Calvo Model

lectures/lqramsey.md, lectures/troubleshooting.md
This PR updates lqramsey to fix Deprecation Warnings
=> [lqramsey] MAINT: fix deprecation warnings

lectures/robustness.md
Fix DeprecationWarning
Fixes #202
=> [robustness] Fix DeprecationWarning

lectures/_static/lecture_specific/chang_credible/changecon.py, lectures/chang_ramsey.md
Fix Runtime and Deprecation warnings
- Avoid invalid inputs by checking and clipping the limits.
- Fix API deprecation warnings by using new API formats.
Fixes #201
=> [chang_ramsey] Fix Runtime and Deprecation warnings

lectures/orth_proj.md
=> [orth_proj] Replace np.sum(a * b) with a @ b

lectures/dyn_stack.md
=> [dyn_stack] Replace np.sum(a * b) with a @ b

lectures/five_preferences.md
=> [five_preferences] Replace np.sum(a * b) with a @ b

lectures/BCG_complete_mkts.md
=> [BCG_complete_mkts] Replace np.sum(a * b) with a @ b

lectures/calvo_machine_learn.md
Replace np.sum(a * b) and jnp.sum(a * b) with a @ b
=> [calvo_machine_learn] Replace np.sum(a * b) with a @ b

.github/workflows/linkcheck.yml
This PR converts the link checker action to use `lychee` on a weekly schedule.
=> MAINT: update linkchecker to use lychee (weekly)

environment.yml, lectures/amss.md
This PR updates to `quantecon-book-theme==0.9.3`
=> FIX: upgrade quantecon-book-theme==0.9.3
