QuantEcon/lecture-python-advanced.myst

lectures/BCG_complete_mkts.md, lectures/amss.md, lectures/amss2.md, lectures/markov_jump_lq.md, lectures/muth_kalman.md, lectures/rob_markov_perf.md, lectures/smoothing.md
update sources from lecture-python-advanced (3cbc32c) using sphinx-tomyst (b06cacb)
This does **not** include `knowing_forceasts_of_others` lecture
=> Update sources from lecture-python-advanced

.github/workflows/ci.yml, .github/workflows/publish.yml, environment.yml
This PR updates GitHub Actions config
=> ENH: Update GitHub Actions

lectures/markov_jump_lq.md
migrates https://github.com/QuantEcon/lecture-python-advanced/pull/175
=> [markov_jump_lq] Correction in math

lectures/matsuyama.md
=> [matsuyama] resize inserted figures

lectures/orth_proj.md, lectures/smoothing.md
Hi @mmcky , this PR fix #51 in lectures:
- https://quantecon.github.io/lecture-python-advanced.myst/orth_proj.html
- https://quantecon.github.io/lecture-python-advanced.myst/smoothing.html
=> [orth_proj] [smoothing] write links implicitly

lectures/additive_functionals.md, lectures/chang_credible.md, lectures/von_neumann_model.md
This PR addresses #64 and #65 in remaining lectures not covered by #69
=> Fix scroll_output and collapse-20 tags for file imports

lectures/_static/lecture_specific/amss/recursive_allocation.py, lectures/_static/lecture_specific/amss2/crra_utility.py, lectures/_static/lecture_specific/amss2/log_utility.py, lectures/_static/lecture_specific/amss2/recursive_allocation.py, lectures/_static/lecture_specific/amss2/sequential_allocation.py, lectures/_static/lecture_specific/amss2/utilities.py, lectures/_static/lecture_specific/opt_tax_recur/crra_utility.py, lectures/_static/lecture_specific/opt_tax_recur/log_utility.py, lectures/_static/lecture_specific/opt_tax_recur/recursive_allocation.py, lectures/_static/lecture_specific/opt_tax_recur/sequential_allocation.py, lectures/amss.md, lectures/amss2.md, lectures/amss3.md, lectures/opt_tax_recur.md
This PR migrates changes from https://github.com/quantecon/lecture-python-advanced for
=> [opt_tax_recur+amss] migrate updates from lecture-python-advanced

lectures/coase.md
=> [coase] center inserted figures

lectures/amss.md, lectures/amss3.md, lectures/arellano.md, lectures/calvo.md, lectures/rosen_schooling_model.md, lectures/smoothing.md, lectures/smoothing_tax.md
Hi @jstac and @oyamad , this PR fix #90 's **list 1**.
=> np.ones * alpha -->> np.full(, alpha)

lectures/_static/lecture_specific/amss2/crra_utility.py, lectures/_static/lecture_specific/amss2/log_utility.py, lectures/_static/lecture_specific/amss2/recursive_allocation.py, lectures/_static/lecture_specific/amss2/sequential_allocation.py, lectures/_static/lecture_specific/opt_tax_recur/recursive_allocation.py, lectures/_static/lecture_specific/opt_tax_recur/sequential_allocation.py
Hi @jstac and @oyamad , this PR fix #90 's patterns in ``py`` files of advanced lectures, identified by @oyamad .
=> np.ones * alpha -->> np.full(, alpah) in py files

.github/workflows/ci.yml, .github/workflows/publish.yml, environment.yml, lectures/_config.yml, lectures/_toc.yml
=> [CI] Update to build pdf using pdflatex

.github/workflows/execution.yml
This PR adds nightly testing against the latest `anaconda` package.
=> MAINT: Adds nightly testing to lectures

lectures/asset_pricing_lph.md
This PR adds some exercises from a converted notebook from Tom. 
I have added `Exercises (Introductory)` and `Exercises (Intermediate)` to avoid too much nesting but the titles become a bit long perhaps.
=> [asset_pricing_lph] add exercises from Tom's notebook

lectures/dyn_stack.md
Fixing issue detected in automatic testing
https://github.com/QuantEcon/QuantEcon.manual/runs/4928922278?check_suite_focus=true
=> FIX: inconsistent titles, moved subproblems to bold

lectures/arellano.md
This fixes missing `code-cell` headers
=> FIX: arellano is missing {code-cell} wrappers

.github/workflows/cache.yml, .github/workflows/ci.yml, .github/workflows/execution.yml, .github/workflows/publish.yml, environment.yml
This updates the `quantecon` environment from `.github`
=> MAINT: Update quantecon environment

lectures/amss.md, lectures/arellano.md, lectures/asset_pricing_lph.md, lectures/classical_filtering.md, lectures/coase.md, lectures/estspec.md, lectures/lqramsey.md, lectures/lu_tricks.md, lectures/lucas_model.md, lectures/matsuyama.md, lectures/smoothing_tax.md
Hi @jstac and @mmcky,
I have migrated the whole advanced series to spinx-exercise (resolved #112).
Please kindly review the latest deployment and merge if it looks good to you.
Many thanks in advance.
=> ENH: Migrate exercise and solutions: Part 2

lectures/BCG_complete_mkts.md, lectures/additive_functionals.md, lectures/black_litterman.md, lectures/calvo.md, lectures/discrete_dp.md, lectures/dyn_stack.md, lectures/estspec.md, lectures/lu_tricks.md, lectures/lucas_model.md, lectures/muth_kalman.md, lectures/opt_tax_recur.md, lectures/robustness.md
Hi @mmcky,
This resolves #122. Could you please merge it if it looks good to you?
Many thanks.
=> Change Hints and Notes to Admonitions

.github/workflows/ci.yml, environment.yml
This PR depends on https://github.com/QuantEcon/QuantEcon.py/pull/664
=> FIX: tauchen API according to new change in PR-664 (QE.py)

lectures/calvo.md
This PR restores Tom's edits after a revert for accidental push
=> [calvo] Restore Tom's edits

.github/workflows/ci.yml, environment.yml
This updates to use the latest `anaconda==2023.03`
=> ENH: Update anaconda==2023.03

lectures/_config.yml
Simply changes the analytics code in the config file to the updated version 4 code.
=> Migrating to Google Analytics 4 with new code

lectures/additive_functionals.md
=> Remove `qe.lss` namespace usage

.github/workflows/ci.yml, lectures/_static/lecture_specific/amss2/recursive_allocation.py, lectures/_static/lecture_specific/amss2/sequential_allocation.py, lectures/_static/lecture_specific/opt_tax_recur/sequential_allocation.py, lectures/amss2.md
=> Fix ValueError in opt_tax_recur.md and amss Lectures

.github/workflows/cache.yml, .github/workflows/ci.yml, .github/workflows/execution.yml, .github/workflows/linkcheck.yml, .github/workflows/publish.yml, environment.yml, lectures/_config.yml, lectures/intro.md, lectures/lqramsey.md, lectures/tax_smoothing_1.md
This PR upgrades to:
- anaconda==2023.09
- python=3.11
- quantecon-book-theme==0.6.0
=> MAINT: Update software stack

lectures/BCG_incomplete_mkts.md
This PR fixes an issue raised by Tom.
=> Hide Code Output in `BCG_incomplete_mkts.md`

lectures/intro.md
Hi @mmcky,
This resolves #151.
Please merge when you are available if it looks good to you. This will help me correct the reorganized intros : )
Many thanks in advance.
=> Remove broken link on intro page

README.md
This PR addresses https://github.com/QuantEcon/meta/issues/132
=> MAINT: standard README

lectures/_config.yml
This PR addresses https://github.com/QuantEcon/meta/issues/137
=> MAINT: update bibtex to author-year

environment.yml
=> TMP: install numba < 0.60 to see if amss is fixed

lectures/calvo_machine_learn.md
This PR contains recent updates on calvo_ml lecture with updated visualizations and one additional regression.
=> [calvo_ml] Updates on Visualizations and Regressions

lectures/calvo.md, lectures/calvo_machine_learn.md
This PR updates calvo lecture with edits from @thomassargent30
=> Tom new calvo edits

lectures/_toc.yml, lectures/calvo.md, lectures/calvo_abreu.md
This PR includes
- updates to the `calvo` lectures
=> Tom October Updates

.github/workflows/cache.yml
This PR fixes the build cache issues for GitHub Actions
=> FIX: jupyter cache

lectures/calvo.md, lectures/calvo_abreu.md
This PR includes improvements to the calvo lecture by @thomassargent30 and @HumphreyYang
=> [calvo] Improvements to the Calvo Lecture

lectures/match_transport.md
This lecture contains the notebook by Tom and Enzo.
=> Add a New Lecture on Composite Sorting

lectures/_static/quant-econ.bib, lectures/calvo.md, lectures/match_transport.md
This PR contains edits and updates to the `calvo` lecture
=> [calvo and match_transport] Edits to Lecture

lectures/calvo_machine_learn.md
Hi @mmcky,
This PR fixes a minor typo in `calvo_machine_learn`. 
Please feel free to merge it if it looks good to you!
=> Update a minor typo in calvo

.github/workflows/ci.yml
This PR updates trigger conditions for `ci.yml`
=> MAINT: update CI to run on PR

lectures/calvo_abreu.md
=> [calvo_abreu] Replace np.sum(a * b) with a @ b

.github/workflows/style-guide.yml
This PR adds the `style-guide` checker (in development and testing)
=> ENH: enable style-guide checker action

.github/workflows/style-guide.yml
Use latest patch of `action-style-guide`
=> UPD: update test action style-guide version to use latest patch

.github/workflows/style-guide.yml
Continue to test action-style-guide with new architecture in `v0.2`
=> ENH: update action-style-guide to v0.2 (testing)
